version: 1.15.0.{build}
branches:
    only:
        - master
skip_tags: true
clone_folder: C:\Cube\Cube.FileSystem.SevenZip
image: Visual Studio 2019 Preview
nuget:
    project_feed: true
    disable_publish_on_pr: true
platform: Any CPU
configuration: Release
before_build:
    - "SET PATH=C:\\Cube\\packages\\OpenCover.4.7.922\\tools;%PATH%"
    - nuget sources add -name Cube.Core -source https://ci.appveyor.com/nuget/cube.core
    - nuget sources add -name Cube.FileSystem -source https://ci.appveyor.com/nuget/cube.filesystem
    - nuget sources add -name Cube.Images -source https://ci.appveyor.com/nuget/cube.images
    - nuget sources add -name Cube.Forms -source https://ci.appveyor.com/nuget/cube.forms
    - rake restore
build:
    parallel: true
    project: Cube.FileSystem.SevenZip.Ice.sln
    publish_nuget: true
    verbosity: minimal
after_build:
    - ps: Start-FileDownload https://ci.appveyor.com/api/projects/clown/7z/artifacts/7z-x64.zip?job=Platform:+x64
    - 7z x -o"..\resources\native\x64\7z" 7z-x64.zip
    - xcopy /Y /I ..\resources\native\x64\7z\7z.* "Tests\bin\Any CPU\Release\net45"
    - xcopy /Y /I ..\resources\native\x64\7z\7z.* "Applications\Ice\Tests\bin\Any CPU\Release\net45"
test_script:
    - >
      OpenCover.Console.exe
      -register:user
      -target:nunit3-console.exe
      -targetargs:Cube.FileSystem.SevenZip.Tests.dll
      -targetdir:"Tests\bin\Any CPU\Release\net45"
      -returntargetcode
      -hideskipped:All
      -output:CoverResults.xml
      -filter:"+[Cube*]* -[*]*NativeMethods -[*]*Properties.*"
    - >
      OpenCover.Console.exe
      -register:user
      -target:nunit3-console.exe
      -targetargs:Cube.FileSystem.SevenZip.Ice.Tests.dll
      -targetdir:"Applications\Ice\Tests\bin\Any CPU\Release\net45"
      -returntargetcode
      -hideskipped:All
      -mergeoutput
      -output:CoverResults.xml
      -filter:"+[Cube*]* -[*]*NativeMethods -[*]*Properties.* -[*]*Form -[*]*.Program"
after_test:
    - xcopy /q /Y /I "Applications\Ice\Progress\bin\Any CPU\Release\net45" CubeIce
    - xcopy /q /Y /I "Applications\Ice\Settings\bin\Any CPU\Release\net45" CubeIce.Settings
    - xcopy /q /Y /I "Applications\Ice\Associate\bin\Any CPU\Release\net45" CubeIce.Settings.Associate
    - xcopy /q /Y /I "Tests\bin\Any CPU\Release\net45\*.log" TestLog\
    - xcopy /q /Y /I "Applications\Ice\Tests\bin\Any CPU\Release\net45\*.log" TestLog\
    - xcopy /q /Y /I CoverResults.xml TestLog\
    - pip install codecov
    - codecov -f CoverResults.xml
artifacts:
    - path: CubeIce
    - path: CubeIce.Settings
    - path: CubeIce.Settings.Associate
    - path: TestLog
