version: 1.15.0.{build}
image: Visual Studio 2019 Preview
platform: Any CPU
configuration: Release
environment:
    PROJECT_NAME:   "Cube.FileSystem.SevenZip"
    PROJECT_BIN:    "bin\\%PLATFORM%\\%CONFIGURATION%\\net45"
    PROJECT_NATIVE: "..\resources\native"
    TEST_TOOL:      "C:\\Cube\\packages\\OpenCover.4.7.922\\tools\\OpenCover.Console.exe"
    TEST_CORETOOL:  "nunit3-console.exe"
    TEST_RESULT:    "TestResults"
    TEST_COVERAGE:  "CoverResults.xml"
branches:
    only:
        - master
skip_tags: true
nuget:
    project_feed: true
    disable_publish_on_pr: true
clone_folder: "C:\\Cube\\%PROJECT_NAME%"
before_build:
    - nuget sources add -name Cube.Core -source https://ci.appveyor.com/nuget/cube.core
    - nuget sources add -name Cube.FileSystem -source https://ci.appveyor.com/nuget/cube.filesystem
    - nuget sources add -name Cube.Images -source https://ci.appveyor.com/nuget/cube.images
    - nuget sources add -name Cube.Forms -source https://ci.appveyor.com/nuget/cube.forms
    - rake restore
build:
    parallel: true
    project: "%PROJECT_NAME%.Ice.sln"
    publish_nuget: true
    verbosity: minimal
after_build:
    - ps: Start-FileDownload https://ci.appveyor.com/api/projects/clown/7z/artifacts/7z-x64.zip?job=Platform:+x64
    - 7z x -o"%PROJECT_NATIVE%\x64\7z" 7z-x64.zip
    - xcopy /Y /I "%PROJECT_NATIVE%\x64\7z\7z.*" "Tests\%PROJECT_BIN%"
    - xcopy /Y /I "%PROJECT_NATIVE%\x64\7z\7z.*" "Applications\Ice\Tests\%PROJECT_BIN%"
test_script:
    - >
      "%TEST_TOOL%"
      -register:user
      -target:"%TEST_CORETOOL%"
      -targetargs:"%PROJECT_NAME%.Tests.dll"
      -targetdir:"Tests\%PROJECT_BIN%"
      -returntargetcode
      -hideskipped:All
      -output:"%TEST_COVERAGE%"
      -filter:"+[Cube*]* -[*]*NativeMethods -[*]*Properties.*"
    - >
      "%TEST_TOOL%"
      -register:user
      -target:"%TEST_CORETOOL%"
      -targetargs:"%PROJECT_NAME%.Ice.Tests.dll"
      -targetdir:"Applications\Ice\Tests\%PROJECT_BIN%"
      -returntargetcode
      -hideskipped:All
      -mergeoutput
      -output:"%TEST_COVERAGE%"
      -filter:"+[Cube*]* -[*]*NativeMethods -[*]*Properties.* -[*]*Form -[*]*.Program"
after_test:
    - xcopy /q /Y /I "Applications\Ice\Progress\%PROJECT_BIN%" "CubeIce"
    - xcopy /q /Y /I "Applications\Ice\Settings\%PROJECT_BIN%" "CubeIce.Settings"
    - xcopy /q /Y /I "Applications\Ice\Associate\%PROJECT_BIN%" "CubeIce.Settings.Associate"
    - xcopy /q /Y /I "Tests\%PROJECT_BIN%\*.log" "%TEST_RESULT%\"
    - xcopy /q /Y /I "Applications\Ice\Tests\%PROJECT_BIN%\*.log" "%TEST_RESULT%\"
    - xcopy /q /Y /I "%TEST_COVERAGE%" "%TEST_RESULT%\"
    - pip install codecov
    - codecov -f "%TEST_COVERAGE%"
artifacts:
    - path: "CubeIce"
    - path: "CubeIce.Settings"
    - path: "CubeIce.Settings.Associate"
    - path: "%TEST_RESULT%"
