version: 1.9.1.{build}
branches:
    only:
        - master
skip_tags: true
clone_folder: C:\Cube\Cube.FileSystem.SevenZip
image: Visual Studio 2017
nuget:
    project_feed: true
    disable_publish_on_pr: true
platform: Any CPU
configuration: Release
before_build:
    - ps: Start-FileDownload https://ci.appveyor.com/api/projects/clown/7z/artifacts/7z-Win32.zip?job=Platform:+Win32
    - ps: Start-FileDownload https://ci.appveyor.com/api/projects/clown/7z/artifacts/7z-x64.zip?job=Platform:+x64
    - 7z x -o"Thirdparty\x86" 7z-Win32.zip
    - 7z x -o"Thirdparty\x64" 7z-x64.zip
    - nuget sources add -name Cube.Core -source https://ci.appveyor.com/nuget/cube.core
    - nuget sources add -name Cube.FileSystem -source https://ci.appveyor.com/nuget/cube.filesystem
    - nuget sources add -name Cube.Images -source https://ci.appveyor.com/nuget/cube.images
    - nuget sources add -name Cube.Forms -source https://ci.appveyor.com/nuget/cube.forms
    - nuget restore Cube.FileSystem.SevenZip.Ice.sln
build:
    parallel: true
    project: Cube.FileSystem.SevenZip.Ice.sln
    publish_nuget: true
    verbosity: minimal
after_build:
    - xcopy /Y /I Applications\Ice\Progress\bin\Release CubeIce
    - xcopy /Y /I Applications\Ice\Settings\bin\Release CubeIce.Settings
    - xcopy /Y /I Applications\Ice\Associate\bin\Release CubeIce.Settings.Associate
    - xcopy /Y /I Thirdparty\x86\7z.* CubeIce\x86
    - xcopy /Y /I Thirdparty\x64\7z.* CubeIce\x64
    - xcopy /Y /I Thirdparty\x64\7z.* Tests\bin\Release
    - xcopy /Y /I Thirdparty\x64\7z.* Applications\Ice\Tests\bin\Release
artifacts:
    - path: CubeIce
    - path: CubeIce.Settings
    - path: CubeIce.Settings.Associate
test_script:
    - >
      ..\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe
      -register:user
      -target:nunit3-console.exe
      -targetargs:Cube.FileSystem.SevenZip.Tests.dll
      -targetdir:Tests\bin\Release
      -returntargetcode
      -hideskipped:All
      -output:CoverResult.xml
      -filter:"+[*]* -[AlphaFS]* -[*]*NativeMethods -[*]*Properties.*"
    - >
      ..\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe
      -register:user
      -target:nunit3-console.exe
      -targetargs:Cube.FileSystem.SevenZip.Ice.Tests.dll
      -targetdir:Applications\Ice\Tests\bin\Release
      -returntargetcode
      -hideskipped:All
      -mergeoutput
      -output:CoverResult.xml
      -filter:"+[*]* -[AlphaFS]* -[*]*NativeMethods -[*]*Properties.* -[*]*Form -[*]*.Program"
after_test:
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f CoverResult.xml