version: 1.4.2.{build}
branches:
    except:
        - net35
skip_tags: true
clone_folder: C:\Cube\Cube.FileSystem
image: Visual Studio 2017
nuget:
    project_feed: true
    disable_publish_on_pr: true
platform: x86
configuration: Release
before_build:
    - ps: Start-FileDownload https://ci.appveyor.com/api/projects/clown/7z/artifacts/7z.dll
    - ps: Start-FileDownload https://ci.appveyor.com/api/projects/clown/7z/artifacts/7z.sfx
    - nuget sources add -name Cube.Core -source https://ci.appveyor.com/nuget/cube.core
    - nuget sources add -name Cube.Images -source https://ci.appveyor.com/nuget/cube.images
    - nuget sources add -name Cube.Forms -source https://ci.appveyor.com/nuget/cube.forms
    - nuget restore Cube.FileSystem.Ice.sln
build:
    parallel: true
    project: Cube.FileSystem.Ice.sln
    publish_nuget: true
    verbosity: normal
after_build:
    - xcopy /Y /I 7z.* Tests\bin\x86\Release
    - xcopy /Y /I 7z.* Applications\Ice.Tests\bin\x86\Release
test_script:
    - ..\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:nunit3-console.exe -targetargs:Cube.FileSystem.Tests.dll -targetdir:Tests\bin\x86\Release -hideskipped:All -output:CoverResult.xml -filter:"+[*]* -[AlphaFS]* -[*]*NativeMethods -[*]*Properties.*"
    - ..\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:nunit3-console.exe -targetargs:Cube.FileSystem.App.Ice.Tests.dll -targetdir:Applications\Ice.Tests\bin\x86\Release -hideskipped:All -mergeoutput -output:CoverResult.xml -filter:"+[*]* -[AlphaFS]* -[*]*NativeMethods -[*]*Properties.* -[*]*Form -[*]*.Program"
after_test:
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f CoverResult.xml