//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cube.FileSystem.App.Ice.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cube.FileSystem.App.Ice.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon Archive {
            get {
                object obj = ResourceManager.GetObject("Archive", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon Extract {
            get {
                object obj = ResourceManager.GetObject("Extract", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   圧縮ファイルを {0} に保存しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageDoneArchive {
            get {
                return ResourceManager.GetString("MessageDoneArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧縮ファイルを {0} に解凍しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageDoneExtract {
            get {
                return ResourceManager.GetString("MessageDoneExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   経過時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageElapsedTime {
            get {
                return ResourceManager.GetString("MessageElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageFileCount {
            get {
                return ResourceManager.GetString("MessageFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを圧縮する準備をしています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessagePreArchive {
            get {
                return ResourceManager.GetString("MessagePreArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを解凍する準備をしています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessagePreExtract {
            get {
                return ResourceManager.GetString("MessagePreExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   残り時間 約 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageRemainTime {
            get {
                return ResourceManager.GetString("MessageRemainTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードの入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitlePassword {
            get {
                return ResourceManager.GetString("TitlePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   β に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VersionSuffix {
            get {
                return ResourceManager.GetString("VersionSuffix", resourceCulture);
            }
        }
    }
}
