//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cube.FileSystem.App.Ice.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cube.FileSystem.App.Ice.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon Archive {
            get {
                object obj = ResourceManager.GetObject("Archive", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon Extract {
            get {
                object obj = ResourceManager.GetObject("Extract", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon File {
            get {
                object obj = ResourceManager.GetObject("File", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon FileAlternate {
            get {
                object obj = ResourceManager.GetObject("FileAlternate", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon FileOld {
            get {
                object obj = ResourceManager.GetObject("FileOld", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   すべてのファイル (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterAll {
            get {
                return ResourceManager.GetString("FilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BZip2 ファイル (*.bz, *.bz2)|*.bz;*.BZ;*.bz2;*.BZ2;*.tbz;*.TBZ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterBzip2 {
            get {
                return ResourceManager.GetString("FilterBzip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GZip ファイル (*.gz)|*.gz;*.GZ;*.tgz;*.TGZ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterGzip {
            get {
                return ResourceManager.GetString("FilterGzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   7z ファイル (*.7z)|*.7z;*.7Z に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterSevenZip {
            get {
                return ResourceManager.GetString("FilterSevenZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tar ファイル (*.tar)|*.tar;*.TAR;*.tar.gz;*.TAR.GZ;*.tar.bz;*.TAR.BZ;*.tar.bz2;*.TAR.BZ2;*.tar.xz;*.TAR.XZ;*.tgz;*.TGZ;*.tbz;*.TBZ;*.txz;*.TXZ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterTar {
            get {
                return ResourceManager.GetString("FilterTar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XZ ファイル (*.xz)|*.xz;*.XZ;*.txz;*.TXZ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterXZ {
            get {
                return ResourceManager.GetString("FilterXZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zip ファイル (*.zip)|*.zip;*.ZIP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterZip {
            get {
                return ResourceManager.GetString("FilterZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap HeaderArchive {
            get {
                object obj = ResourceManager.GetObject("HeaderArchive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap HeaderExtract {
            get {
                object obj = ResourceManager.GetObject("HeaderExtract", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   最速 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LevelFast {
            get {
                return ResourceManager.GetString("LevelFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   高圧縮 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LevelHigh {
            get {
                return ResourceManager.GetString("LevelHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   高速 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LevelLow {
            get {
                return ResourceManager.GetString("LevelLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無圧縮 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LevelNone {
            get {
                return ResourceManager.GetString("LevelNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   標準 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LevelNormal {
            get {
                return ResourceManager.GetString("LevelNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最高圧縮 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LevelUltra {
            get {
                return ResourceManager.GetString("LevelUltra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再開 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuResume {
            get {
                return ResourceManager.GetString("MenuResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中断 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSuspend {
            get {
                return ResourceManager.GetString("MenuSuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} を作成しています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageArchive {
            get {
                return ResourceManager.GetString("MessageArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageCurrentFile {
            get {
                return ResourceManager.GetString("MessageCurrentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} に保存しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageDoneArchive {
            get {
                return ResourceManager.GetString("MessageDoneArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} に解凍しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageDoneExtract {
            get {
                return ResourceManager.GetString("MessageDoneExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   経過時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageElapsedTime {
            get {
                return ResourceManager.GetString("MessageElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解凍したファイルを保存するフォルダを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageExtractDestination {
            get {
                return ResourceManager.GetString("MessageExtractDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageFileCount {
            get {
                return ResourceManager.GetString("MessageFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageFileSize {
            get {
                return ResourceManager.GetString("MessageFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageLastWriteTime {
            get {
                return ResourceManager.GetString("MessageLastWriteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageNewFile {
            get {
                return ResourceManager.GetString("MessageNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この場所には同じ名前のファイルが既に存在します。上書きしますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageOverwrite {
            get {
                return ResourceManager.GetString("MessageOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを圧縮する準備をしています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessagePreArchive {
            get {
                return ResourceManager.GetString("MessagePreArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを解凍する準備をしています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessagePreExtract {
            get {
                return ResourceManager.GetString("MessagePreExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   残り時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageRemainTime {
            get {
                return ResourceManager.GetString("MessageRemainTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明なファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageUnknownFile {
            get {
                return ResourceManager.GetString("MessageUnknownFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードの入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitlePassword {
            get {
                return ResourceManager.GetString("TitlePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   β に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VersionSuffix {
            get {
                return ResourceManager.GetString("VersionSuffix", resourceCulture);
            }
        }
    }
}
