//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cube.FileSystem.SevenZip.Ice.Settings.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cube.FileSystem.SevenZip.Ice.Settings.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Archive {
            get {
                object obj = ResourceManager.GetObject("Archive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Extract {
            get {
                object obj = ResourceManager.GetObject("Extract", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to cubeice-associate.exe.
        /// </summary>
        internal static string FileAssociate {
            get {
                return ResourceManager.GetString("FileAssociate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FileV1Icon {
            get {
                object obj = ResourceManager.GetObject("FileV1Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FileV2Icon {
            get {
                object obj = ResourceManager.GetObject("FileV2Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FileV3Icon {
            get {
                object obj = ResourceManager.GetObject("FileV3Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 最速.
        /// </summary>
        internal static string LevelFast {
            get {
                return ResourceManager.GetString("LevelFast", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 高圧縮.
        /// </summary>
        internal static string LevelHigh {
            get {
                return ResourceManager.GetString("LevelHigh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 高速.
        /// </summary>
        internal static string LevelLow {
            get {
                return ResourceManager.GetString("LevelLow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 無圧縮.
        /// </summary>
        internal static string LevelNone {
            get {
                return ResourceManager.GetString("LevelNone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 標準.
        /// </summary>
        internal static string LevelNormal {
            get {
                return ResourceManager.GetString("LevelNormal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 最高圧縮.
        /// </summary>
        internal static string LevelUltra {
            get {
                return ResourceManager.GetString("LevelUltra", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to メニューを追加.
        /// </summary>
        internal static string MenuAdd {
            get {
                return ResourceManager.GetString("MenuAdd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BZip2.
        /// </summary>
        internal static string MenuBZip2 {
            get {
                return ResourceManager.GetString("MenuBZip2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to デスクトップに解凍.
        /// </summary>
        internal static string MenuDesktop {
            get {
                return ResourceManager.GetString("MenuDesktop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 詳細設定.
        /// </summary>
        internal static string MenuDetails {
            get {
                return ResourceManager.GetString("MenuDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 下に移動.
        /// </summary>
        internal static string MenuDown {
            get {
                return ResourceManager.GetString("MenuDown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 拡張.
        /// </summary>
        internal static string MenuExtended {
            get {
                return ResourceManager.GetString("MenuExtended", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GZip.
        /// </summary>
        internal static string MenuGZip {
            get {
                return ResourceManager.GetString("MenuGZip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ここに解凍.
        /// </summary>
        internal static string MenuHere {
            get {
                return ResourceManager.GetString("MenuHere", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to マイドキュメントに解凍.
        /// </summary>
        internal static string MenuMyDocuments {
            get {
                return ResourceManager.GetString("MenuMyDocuments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 新しいカテゴリー.
        /// </summary>
        internal static string MenuNewCategory {
            get {
                return ResourceManager.GetString("MenuNewCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 標準.
        /// </summary>
        internal static string MenuNormal {
            get {
                return ResourceManager.GetString("MenuNormal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        internal static string MenuRemove {
            get {
                return ResourceManager.GetString("MenuRemove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 名前を変更.
        /// </summary>
        internal static string MenuRename {
            get {
                return ResourceManager.GetString("MenuRename", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 場所を指定して解凍.
        /// </summary>
        internal static string MenuRuntime {
            get {
                return ResourceManager.GetString("MenuRuntime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 7-Zip.
        /// </summary>
        internal static string MenuSevenZip {
            get {
                return ResourceManager.GetString("MenuSevenZip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 自己解凍形式.
        /// </summary>
        internal static string MenuSfx {
            get {
                return ResourceManager.GetString("MenuSfx", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to メニュートップ.
        /// </summary>
        internal static string MenuTop {
            get {
                return ResourceManager.GetString("MenuTop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 上に移動.
        /// </summary>
        internal static string MenuUp {
            get {
                return ResourceManager.GetString("MenuUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to XZ.
        /// </summary>
        internal static string MenuXZ {
            get {
                return ResourceManager.GetString("MenuXZ", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        internal static string MenuZip {
            get {
                return ResourceManager.GetString("MenuZip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zip（パスワード）.
        /// </summary>
        internal static string MenuZipPassword {
            get {
                return ResourceManager.GetString("MenuZipPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ファイル名に次の文字を使用する事はできません.
        /// </summary>
        internal static string MessageInvalidChars {
            get {
                return ResourceManager.GetString("MessageInvalidChars", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 圧縮・解凍したファイルの保存または作業用フォルダーを選択して下さい。.
        /// </summary>
        internal static string MessageSave {
            get {
                return ResourceManager.GetString("MessageSave", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://www.cube-soft.jp/.
        /// </summary>
        internal static string WebPage {
            get {
                return ResourceManager.GetString("WebPage", resourceCulture);
            }
        }
    }
}
