//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cube.FileSystem.SevenZip.App.Ice.Settings.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cube.FileSystem.SevenZip.App.Ice.Settings.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   cubeice-associate.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileAssociate {
            get {
                return ResourceManager.GetString("FileAssociate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   BZip2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuBZip2 {
            get {
                return ResourceManager.GetString("MenuBZip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デスクトップに解凍 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuDesktop {
            get {
                return ResourceManager.GetString("MenuDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳細設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuDetail {
            get {
                return ResourceManager.GetString("MenuDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GZip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuGZip {
            get {
                return ResourceManager.GetString("MenuGZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ここに解凍 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuHere {
            get {
                return ResourceManager.GetString("MenuHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイドキュメントに解凍 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuMyDocuments {
            get {
                return ResourceManager.GetString("MenuMyDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   場所を指定して解凍 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuRuntime {
            get {
                return ResourceManager.GetString("MenuRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   7-Zip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSevenZip {
            get {
                return ResourceManager.GetString("MenuSevenZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自己解凍形式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSfx {
            get {
                return ResourceManager.GetString("MenuSfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XZ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuXZ {
            get {
                return ResourceManager.GetString("MenuXZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuZip {
            get {
                return ResourceManager.GetString("MenuZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zip（パスワード） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuZipPassword {
            get {
                return ResourceManager.GetString("MenuZipPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧縮または解凍したファイルを保存するフォルダを選択して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageSave {
            get {
                return ResourceManager.GetString("MessageSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   http://www.cube-soft.jp/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WebPage {
            get {
                return ResourceManager.GetString("WebPage", resourceCulture);
            }
        }
    }
}
