//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cube.FileSystem.SevenZip.Ice.Properties {
    using System;

    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cube.FileSystem.SevenZip.Ice.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーを無視して処理を継続しますか？継続した場合、圧縮・解凍結果の一部または全部が破損している可能性があるのでご注意下さい。.
        /// </summary>
        internal static string ErrorContinue {
            get {
                return ResourceManager.GetString("ErrorContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 処理中にエラーが発生しました ({0})。.
        /// </summary>
        internal static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7-Zip ファイル.
        /// </summary>
        internal static string Filter7z {
            get {
                return ResourceManager.GetString("Filter7z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すべてのファイル.
        /// </summary>
        internal static string FilterAll {
            get {
                return ResourceManager.GetString("FilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BZip2 ファイル.
        /// </summary>
        internal static string FilterBz2 {
            get {
                return ResourceManager.GetString("FilterBz2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GZip ファイル.
        /// </summary>
        internal static string FilterGz {
            get {
                return ResourceManager.GetString("FilterGz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自己解凍形式ファイル.
        /// </summary>
        internal static string FilterSfx {
            get {
                return ResourceManager.GetString("FilterSfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tar ファイル.
        /// </summary>
        internal static string FilterTar {
            get {
                return ResourceManager.GetString("FilterTar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XZ ファイル.
        /// </summary>
        internal static string FilterXz {
            get {
                return ResourceManager.GetString("FilterXz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip ファイル.
        /// </summary>
        internal static string FilterZip {
            get {
                return ResourceManager.GetString("FilterZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自己解凍形式.
        /// </summary>
        internal static string FormatSfx {
            get {
                return ResourceManager.GetString("FormatSfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hero {
            get {
                object obj = ResourceManager.GetObject("Hero", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最速.
        /// </summary>
        internal static string LevelFast {
            get {
                return ResourceManager.GetString("LevelFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高圧縮.
        /// </summary>
        internal static string LevelHigh {
            get {
                return ResourceManager.GetString("LevelHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高速.
        /// </summary>
        internal static string LevelLow {
            get {
                return ResourceManager.GetString("LevelLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無圧縮.
        /// </summary>
        internal static string LevelNone {
            get {
                return ResourceManager.GetString("LevelNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 標準.
        /// </summary>
        internal static string LevelNormal {
            get {
                return ResourceManager.GetString("LevelNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最高圧縮.
        /// </summary>
        internal static string LevelUltra {
            get {
                return ResourceManager.GetString("LevelUltra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 再開.
        /// </summary>
        internal static string MenuResume {
            get {
                return ResourceManager.GetString("MenuResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一時停止.
        /// </summary>
        internal static string MenuSuspend {
            get {
                return ResourceManager.GetString("MenuSuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} を作成しています....
        /// </summary>
        internal static string MessageArchive {
            get {
                return ResourceManager.GetString("MessageArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} に保存しました。.
        /// </summary>
        internal static string MessageArchiveSuccess {
            get {
                return ResourceManager.GetString("MessageArchiveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サイズ.
        /// </summary>
        internal static string MessageBytes {
            get {
                return ResourceManager.GetString("MessageBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル数.
        /// </summary>
        internal static string MessageCount {
            get {
                return ResourceManager.GetString("MessageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在のファイル.
        /// </summary>
        internal static string MessageCurrent {
            get {
                return ResourceManager.GetString("MessageCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 経過時間.
        /// </summary>
        internal static string MessageElapseTime {
            get {
                return ResourceManager.GetString("MessageElapseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解凍したファイルを保存するフォルダを選択してください。.
        /// </summary>
        internal static string MessageExtractDestination {
            get {
                return ResourceManager.GetString("MessageExtractDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} に解凍しました。.
        /// </summary>
        internal static string MessageExtractSuccess {
            get {
                return ResourceManager.GetString("MessageExtractSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル名に次の文字を使用する事はできません.
        /// </summary>
        internal static string MessageInvalidChars {
            get {
                return ResourceManager.GetString("MessageInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新日時.
        /// </summary>
        internal static string MessageLastWriteTime {
            get {
                return ResourceManager.GetString("MessageLastWriteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しいファイル.
        /// </summary>
        internal static string MessageNewFile {
            get {
                return ResourceManager.GetString("MessageNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この場所には同じ名前のファイルが既に存在します。上書きしますか？.
        /// </summary>
        internal static string MessageOverwrite {
            get {
                return ResourceManager.GetString("MessageOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルを圧縮する準備をしています。この操作には数分かかる事があります。.
        /// </summary>
        internal static string MessagePreArchive {
            get {
                return ResourceManager.GetString("MessagePreArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルを解凍する準備をしています。この操作には数分かかる事があります。.
        /// </summary>
        internal static string MessagePreExtract {
            get {
                return ResourceManager.GetString("MessagePreExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 残り時間.
        /// </summary>
        internal static string MessageRemainTime {
            get {
                return ResourceManager.GetString("MessageRemainTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 予期しないエラーが発生しました。.
        /// </summary>
        internal static string MessageUnexpectedError {
            get {
                return ResourceManager.GetString("MessageUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不明なファイル.
        /// </summary>
        internal static string MessageUnknownFile {
            get {
                return ResourceManager.GetString("MessageUnknownFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定されたファイルは未対応の圧縮形式か、または圧縮ファイルではないため解凍する事ができません。もう1度ファイルの内容を確認して下さい。.
        /// </summary>
        internal static string MessageUnkownFormat {
            get {
                return ResourceManager.GetString("MessageUnkownFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CubeICE.
        /// </summary>
        internal static string TitleDefault {
            get {
                return ResourceManager.GetString("TitleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CubeICE エラー.
        /// </summary>
        internal static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードの入力.
        /// </summary>
        internal static string TitlePassword {
            get {
                return ResourceManager.GetString("TitlePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to β.
        /// </summary>
        internal static string VersionSuffix {
            get {
                return ResourceManager.GetString("VersionSuffix", resourceCulture);
            }
        }
    }
}
