//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cube.FileSystem.SevenZip.Ice.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cube.FileSystem.SevenZip.Ice.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   圧縮 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CtxArchive {
            get {
                return ResourceManager.GetString("CtxArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BZip2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CtxBZip2 {
            get {
                return ResourceManager.GetString("CtxBZip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デスクトップに解凍 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CtxDesktop {
            get {
                return ResourceManager.GetString("CtxDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳細設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CtxDetails {
            get {
                return ResourceManager.GetString("CtxDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解凍 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CtxExtract {
            get {
                return ResourceManager.GetString("CtxExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GZip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CtxGZip {
            get {
                return ResourceManager.GetString("CtxGZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧縮してメール送信 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CtxMail {
            get {
                return ResourceManager.GetString("CtxMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイドキュメントに解凍 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CtxMyDocuments {
            get {
                return ResourceManager.GetString("CtxMyDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   場所を指定して解凍 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CtxRuntime {
            get {
                return ResourceManager.GetString("CtxRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   7-Zip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CtxSevenZip {
            get {
                return ResourceManager.GetString("CtxSevenZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自己解凍形式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CtxSfx {
            get {
                return ResourceManager.GetString("CtxSfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ここに解凍 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CtxSource {
            get {
                return ResourceManager.GetString("CtxSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Xz に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CtxXz {
            get {
                return ResourceManager.GetString("CtxXz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CtxZip {
            get {
                return ResourceManager.GetString("CtxZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zip (パスワード) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CtxZipPassword {
            get {
                return ResourceManager.GetString("CtxZipPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSuffix {
            get {
                return ResourceManager.GetString("FileSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CubeICE 圧縮 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ScArcive {
            get {
                return ResourceManager.GetString("ScArcive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CubeICE 解凍 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ScExtract {
            get {
                return ResourceManager.GetString("ScExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CubeICE 設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ScSettings {
            get {
                return ResourceManager.GetString("ScSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   β に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VersionSuffix {
            get {
                return ResourceManager.GetString("VersionSuffix", resourceCulture);
            }
        }
    }
}
