//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cube.FileSystem.SevenZip.Ice.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cube.FileSystem.SevenZip.Ice.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 7-Zip.
        /// </summary>
        internal static string Ctx7z {
            get {
                return ResourceManager.GetString("Ctx7z", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 圧縮.
        /// </summary>
        internal static string CtxArchive {
            get {
                return ResourceManager.GetString("CtxArchive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BZip2.
        /// </summary>
        internal static string CtxBz2 {
            get {
                return ResourceManager.GetString("CtxBz2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to デスクトップに解凍.
        /// </summary>
        internal static string CtxDesktop {
            get {
                return ResourceManager.GetString("CtxDesktop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 詳細設定.
        /// </summary>
        internal static string CtxDetails {
            get {
                return ResourceManager.GetString("CtxDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 解凍.
        /// </summary>
        internal static string CtxExtract {
            get {
                return ResourceManager.GetString("CtxExtract", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GZip.
        /// </summary>
        internal static string CtxGz {
            get {
                return ResourceManager.GetString("CtxGz", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 圧縮してメール送信.
        /// </summary>
        internal static string CtxMail {
            get {
                return ResourceManager.GetString("CtxMail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to マイドキュメントに解凍.
        /// </summary>
        internal static string CtxMyDocuments {
            get {
                return ResourceManager.GetString("CtxMyDocuments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 場所を指定して解凍.
        /// </summary>
        internal static string CtxQuery {
            get {
                return ResourceManager.GetString("CtxQuery", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 自己解凍形式.
        /// </summary>
        internal static string CtxSfx {
            get {
                return ResourceManager.GetString("CtxSfx", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ここに解凍.
        /// </summary>
        internal static string CtxSource {
            get {
                return ResourceManager.GetString("CtxSource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Xz.
        /// </summary>
        internal static string CtxXz {
            get {
                return ResourceManager.GetString("CtxXz", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        internal static string CtxZip {
            get {
                return ResourceManager.GetString("CtxZip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zip (パスワード).
        /// </summary>
        internal static string CtxZipPassword {
            get {
                return ResourceManager.GetString("CtxZipPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CubeICE 圧縮.
        /// </summary>
        internal static string ScArcive {
            get {
                return ResourceManager.GetString("ScArcive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CubeICE 解凍.
        /// </summary>
        internal static string ScExtract {
            get {
                return ResourceManager.GetString("ScExtract", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CubeICE 設定.
        /// </summary>
        internal static string ScSettings {
            get {
                return ResourceManager.GetString("ScSettings", resourceCulture);
            }
        }
    }
}
